import { SANS, SERIF } from '../fonts'
import type { Theme } from '../types'

/** 经典：衬线标题 + 陶土橙强调，克制干净 */
export const classicTheme: Theme = {
  id: 'classic',
  name: '经典',
  description: '衬线标题 + 陶土橙强调，克制干净',
  body: {
    font: SANS,
    fontSize: '16px',
    lineHeight: '1.75',
    color: '#2b2b2b',
  },
  accent: '#d97757',
  heading: {
    font: SERIF,
    fontWeight: '700',
    color: '#1a1a1a',
    lineHeight: '1.4',
    letterSpacing: '0.5px',
    marginTop: '28px',
    marginBottom: '12px',
    decor: 'none',
  },
  headingSizes: {
    h1: '28px',
    h2: '24px',
    h3: '21px',
    h4: '19px',
    h5: '17px',
    h6: '16px',
  },
  pMargin: '16px',
  quote: {
    background: '#faf6f2',
    color: '#4a4a45',
    borderLeft: '4px solid #d97757',
    borderRadius: '0 6px 6px 0',
    padding: '12px 16px',
    margin: '20px 0',
  },
  callout: {
    background: '#f2efe8',
    color: '#4a4a45',
    borderLeft: '4px solid #d97757',
    borderRadius: '0 10px 10px 0',
    padding: '14px 16px',
    margin: '20px 0',
  },
  code: {
    background: '#f4f1ec',
    color: '#26231e',
    borderRadius: '4px',
    padding: '2px 5px',
    fontSize: '0.9em',
  },
  codeBlock: {
    background: '#f7f5f0',
    color: '#2b2823',
    borderRadius: '6px',
    padding: '14px 16px',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  link: { color: '#d97757', textDecoration: 'underline' },
  listPaddingLeft: '26px',
  listItemMargin: '6px 0',
  table: {
    borderColor: '#e5e3dc',
    headBg: '#f4f1ec',
    headColor: '#26231e',
    fontSize: '15px',
    cellPadding: '8px 12px',
  },
  hr: { color: '#e5e3dc', margin: '28px 0' },
  img: { borderRadius: '8px', margin: '16px auto' },
  strongColor: 'inherit',
  delColor: '#a6a29a',
  mark: {
    background: '#fff3c4',
    color: '#4a3a10',
    borderRadius: '3px',
    padding: '1px 4px',
  },
  footnote: {
    refColor: '#d97757',
    blockBorder: '#e5e3dc',
    textColor: '#8a867e',
    numColor: '#d97757',
    textSize: '12px',
  },
}
