import { SANS, SERIF } from '../fonts'
import type { Theme } from '../types'

/** 杂志编辑：绯红强调 + 重磅衬线大标题 + 报刊引语，纸媒编辑部气质 */
export const editorialTheme: Theme = {
  id: 'editorial',
  name: '杂志编辑',
  description: '绯红强调 + 重磅衬线标题 + 报刊引语',
  body: { font: SANS, fontSize: '16px', lineHeight: '1.9', color: '#22211e' },
  accent: '#c43a2d',
  accentSoft: 'rgba(196,58,45,.09)',
  heading: {
    font: SERIF,
    fontWeight: '800',
    color: '#14120e',
    lineHeight: '1.22',
    letterSpacing: '0.5px',
    marginTop: '40px',
    marginBottom: '16px',
    decor: 'rule',
  },
  headingSizes: {
    h1: '32px',
    h2: '27px',
    h3: '22px',
    h4: '19px',
    h5: '17px',
    h6: '16px',
  },
  pMargin: '20px',
  quote: {
    background: 'transparent',
    color: '#6b4a3f',
    borderLeft: '3px solid #c43a2d',
    borderRadius: '0',
    padding: '6px 0 6px 20px',
    margin: '26px 0',
    fontStyle: 'italic',
    extra: {
      'font-family': SERIF,
      'font-size': '18px',
      'line-height': '1.8',
    },
  },
  callout: {
    background: 'rgba(196,58,45,.05)',
    color: '#5a463c',
    borderLeft: '3px solid #c43a2d',
    borderRadius: '0',
    padding: '14px 18px',
    margin: '26px 0',
  },
  code: {
    background: '#f0ece5',
    color: '#c43a2d',
    borderRadius: '3px',
    padding: '1px 5px',
    fontSize: '0.85em',
  },
  codeBlock: {
    background: '#f3efe9',
    color: '#2a2722',
    borderRadius: '0',
    padding: '18px 20px',
    fontSize: '14px',
    lineHeight: '1.7',
  },
  link: { color: '#c43a2d', textDecoration: 'underline' },
  listPaddingLeft: '26px',
  listItemMargin: '8px 0',
  table: {
    borderColor: '#d9d3c8',
    headBg: '#14120e',
    headColor: '#f5f0e6',
    fontSize: '15px',
    cellPadding: '9px 12px',
  },
  hr: { color: '#c43a2d', margin: '32px 0' },
  img: { borderRadius: '0', margin: '20px auto' },
  strongColor: '#c43a2d',
  delColor: '#a39c90',
  mark: {
    background: '#ffe9a8',
    color: '#4a3a10',
    borderRadius: '2px',
    padding: '1px 4px',
  },
  footnote: {
    refColor: '#c43a2d',
    blockBorder: '#d9d3c8',
    textColor: '#8a8376',
    numColor: '#c43a2d',
    textSize: '12px',
  },
}
