import { SANS } from '../fonts'
import type { Theme } from '../types'

/** 静蓝笔记：靛蓝强调 + 冷灰正文，技术文档气质 */
export const indigoTheme: Theme = {
  id: 'indigo',
  name: '静蓝笔记',
  description: '靛蓝强调 + 冷灰正文，技术文档气质',
  body: { font: SANS, fontSize: '16px', lineHeight: '1.8', color: '#2f3540' },
  accent: '#3f6ecc',
  accentSoft: 'rgba(63,110,204,.10)',
  heading: {
    font: SANS,
    fontWeight: '700',
    color: '#1b2430',
    lineHeight: '1.42',
    letterSpacing: '0.2px',
    marginTop: '30px',
    marginBottom: '13px',
    decor: 'accent-bar',
  },
  headingSizes: {
    h1: '27px',
    h2: '23px',
    h3: '20px',
    h4: '18px',
    h5: '17px',
    h6: '16px',
  },
  pMargin: '17px',
  quote: {
    background: '#f3f6fc',
    color: '#44505f',
    borderLeft: '3px solid #3f6ecc',
    borderRadius: '0 8px 8px 0',
    padding: '12px 16px',
    margin: '22px 0',
  },
  callout: {
    background: 'rgba(63,110,204,.08)',
    color: '#3a4657',
    borderLeft: '3px solid #3f6ecc',
    borderRadius: '0 10px 10px 0',
    padding: '14px 16px',
    margin: '22px 0',
    badgeColor: '#2f58ad',
  },
  code: {
    background: '#eef2f9',
    color: '#2b3648',
    borderRadius: '4px',
    padding: '2px 5px',
    fontSize: '0.9em',
  },
  codeBlock: {
    background: '#f5f7fb',
    color: '#2b3648',
    borderRadius: '8px',
    padding: '14px 16px',
    fontSize: '14px',
    lineHeight: '1.62',
  },
  link: { color: '#3f6ecc', textDecoration: 'underline' },
  listPaddingLeft: '26px',
  listItemMargin: '6px 0',
  table: {
    borderColor: '#dde4ef',
    headBg: '#eef2f9',
    headColor: '#2b3648',
    fontSize: '15px',
    cellPadding: '8px 12px',
  },
  hr: { color: '#dde4ef', margin: '30px 0' },
  img: { borderRadius: '8px', margin: '18px auto' },
  strongColor: '#1b2430',
  delColor: '#9aa3b0',
  mark: {
    background: '#dbe7ff',
    color: '#22355c',
    borderRadius: '3px',
    padding: '1px 4px',
  },
  footnote: {
    refColor: '#3f6ecc',
    blockBorder: '#dde4ef',
    textColor: '#7d8797',
    numColor: '#3f6ecc',
    textSize: '12px',
  },
}
