import { SERIF } from '../fonts'
import type { Theme } from '../types'

/** 松墨：墨绿强调 + 宋体标题 + 大留白，东方书卷气 */
export const inkTheme: Theme = {
  id: 'ink',
  name: '松墨',
  description: '墨绿强调 + 宋体标题 + 大留白，书卷气',
  body: {
    font: SERIF,
    fontSize: '16.5px',
    lineHeight: '1.95',
    color: '#33352f',
  },
  accent: '#4a6b52',
  accentSoft: 'rgba(74,107,82,.10)',
  heading: {
    font: SERIF,
    fontWeight: '700',
    color: '#232620',
    lineHeight: '1.5',
    letterSpacing: '1.5px',
    marginTop: '34px',
    marginBottom: '15px',
    decor: 'none',
  },
  headingSizes: {
    h1: '27px',
    h2: '23px',
    h3: '20px',
    h4: '18px',
    h5: '17px',
    h6: '16px',
  },
  pMargin: '19px',
  quote: {
    background: 'transparent',
    color: '#55584f',
    borderLeft: '2px solid #4a6b52',
    borderRadius: '0',
    padding: '4px 0 4px 18px',
    margin: '26px 0',
    fontStyle: 'italic',
  },
  callout: {
    background: 'rgba(74,107,82,.07)',
    color: '#434639',
    borderLeft: '2px solid #4a6b52',
    borderRadius: '0 8px 8px 0',
    padding: '14px 18px',
    margin: '26px 0',
    badgeColor: '#3d5a44',
  },
  code: {
    background: '#f0f1ea',
    color: '#2f322b',
    borderRadius: '3px',
    padding: '2px 5px',
    fontSize: '0.88em',
  },
  codeBlock: {
    background: '#f4f5ee',
    color: '#2f322b',
    borderRadius: '4px',
    padding: '15px 17px',
    fontSize: '13.5px',
    lineHeight: '1.68',
  },
  link: { color: '#4a6b52', textDecoration: 'underline' },
  listPaddingLeft: '25px',
  listItemMargin: '8px 0',
  table: {
    borderColor: '#e0e1d8',
    headBg: '#f0f1ea',
    headColor: '#2f322b',
    fontSize: '15px',
    cellPadding: '9px 13px',
  },
  hr: { color: '#dcded3', margin: '34px 0' },
  img: { borderRadius: '2px', margin: '20px auto' },
  strongColor: '#232620',
  delColor: '#a3a59b',
  mark: {
    background: '#e6ecd9',
    color: '#333720',
    borderRadius: '2px',
    padding: '1px 4px',
  },
  footnote: {
    refColor: '#4a6b52',
    blockBorder: '#dcdede',
    textColor: '#847f76',
    numColor: '#4a6b52',
    textSize: '12px',
  },
}
