import { SANS } from '../fonts'
import type { Theme } from '../types'

/** 极简灰：无强调装饰 + 中性灰阶，纯粹排版 */
export const minimalTheme: Theme = {
  id: 'minimal',
  name: '极简灰',
  description: '中性灰阶 + 零装饰，只剩排版本身',
  body: { font: SANS, fontSize: '16px', lineHeight: '1.8', color: '#3a3a3a' },
  accent: '#5c5c5c',
  accentSoft: 'rgba(92,92,92,.08)',
  heading: {
    font: SANS,
    fontWeight: '600',
    color: '#171717',
    lineHeight: '1.4',
    letterSpacing: '-0.2px',
    marginTop: '32px',
    marginBottom: '12px',
    decor: 'none',
  },
  headingSizes: {
    h1: '26px',
    h2: '22px',
    h3: '19px',
    h4: '17px',
    h5: '16px',
    h6: '15px',
  },
  pMargin: '16px',
  quote: {
    background: 'transparent',
    color: '#5c5c5c',
    borderLeft: '3px solid #d4d4d4',
    borderRadius: '0',
    padding: '2px 0 2px 16px',
    margin: '22px 0',
  },
  callout: {
    background: '#f5f5f5',
    color: '#454545',
    borderLeft: '3px solid #a3a3a3',
    borderRadius: '0 6px 6px 0',
    padding: '13px 16px',
    margin: '22px 0',
    badgeColor: '#262626',
  },
  code: {
    background: '#f0f0f0',
    color: '#262626',
    borderRadius: '3px',
    padding: '2px 5px',
    fontSize: '0.9em',
  },
  codeBlock: {
    background: '#fafafa',
    color: '#292929',
    borderRadius: '6px',
    padding: '14px 16px',
    fontSize: '13.5px',
    lineHeight: '1.62',
    extra: { border: '1px solid #ebebeb' },
  },
  link: { color: '#171717', textDecoration: 'underline' },
  listPaddingLeft: '25px',
  listItemMargin: '6px 0',
  table: {
    borderColor: '#e0e0e0',
    headBg: '#f5f5f5',
    headColor: '#262626',
    fontSize: '15px',
    cellPadding: '8px 12px',
  },
  hr: { color: '#e0e0e0', margin: '32px 0' },
  img: { borderRadius: '4px', margin: '18px auto' },
  strongColor: '#171717',
  delColor: '#a3a3a3',
  mark: {
    background: '#ececec',
    color: '#171717',
    borderRadius: '2px',
    padding: '1px 4px',
  },
  footnote: {
    refColor: '#5c5c5c',
    blockBorder: '#e0e0e0',
    textColor: '#8a8a8a',
    numColor: '#5c5c5c',
    textSize: '12px',
  },
}
