import { SANS } from '../fonts'
import type { Theme } from '../types'

/** 樱雪：柔粉强调 + 圆润卡片，轻盈少女感 */
export const sakuraTheme: Theme = {
  id: 'sakura',
  name: '樱雪',
  description: '柔粉强调 + 圆润卡片，轻盈通透',
  body: {
    font: SANS,
    fontSize: '16px',
    lineHeight: '1.85',
    color: '#4a3f45',
  },
  accent: '#d9628a',
  accentSoft: 'rgba(217,98,138,.10)',
  heading: {
    font: SANS,
    fontWeight: '700',
    color: '#3d2f36',
    lineHeight: '1.45',
    letterSpacing: '0.3px',
    marginTop: '30px',
    marginBottom: '13px',
    decor: 'band',
  },
  headingSizes: {
    h1: '27px',
    h2: '23px',
    h3: '20px',
    h4: '18px',
    h5: '17px',
    h6: '16px',
  },
  pMargin: '17px',
  quote: {
    background: '#fdeef4',
    color: '#5a4a52',
    borderLeft: 'none',
    borderRadius: '12px',
    padding: '14px 18px',
    margin: '22px 0',
  },
  callout: {
    background: '#fce8f0',
    color: '#59444e',
    borderLeft: 'none',
    borderRadius: '14px',
    padding: '15px 18px',
    margin: '22px 0',
    badgeColor: '#c14a76',
  },
  code: {
    background: '#fbeaf1',
    color: '#6d3b50',
    borderRadius: '5px',
    padding: '2px 6px',
    fontSize: '0.9em',
  },
  codeBlock: {
    background: '#fdf2f6',
    color: '#4a3540',
    borderRadius: '12px',
    padding: '15px 17px',
    fontSize: '14px',
    lineHeight: '1.62',
  },
  link: { color: '#d9628a', textDecoration: 'underline' },
  listPaddingLeft: '26px',
  listItemMargin: '7px 0',
  table: {
    borderColor: '#f3dae4',
    headBg: '#fceaf2',
    headColor: '#5c3f4c',
    fontSize: '15px',
    cellPadding: '8px 12px',
  },
  hr: { color: '#f3dae4', margin: '30px 0' },
  img: { borderRadius: '14px', margin: '18px auto' },
  strongColor: '#c14a76',
  delColor: '#b9a8af',
  mark: {
    background: '#ffe0ec',
    color: '#7a2f4d',
    borderRadius: '4px',
    padding: '1px 5px',
  },
  footnote: {
    refColor: '#d9628a',
    blockBorder: '#f3dae4',
    textColor: '#95848c',
    numColor: '#d9628a',
    textSize: '12px',
  },
}
